routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('/articles/{title?}/{article}', 'ArticlesController@show')->name('article');
Route::get('/categories/{categoryName}', 'CategoriesController@show')->name('category');

Auth::routes();

Route::group(config('routes.dashboard'), function() {
    Route::get('/', 'IndexController@index')->name('index');

    /**
     * Article routes
     */
    Route::post('/articles/{article}/restore', 'ArticlesController@restore')->name('articles.restore');
    Route::delete('/articles/{article}/delete', 'ArticlesController@delete')->name('articles.delete');
    Route::resource('/articles', 'ArticlesController');

    /**
     * Category routes
     */
    Route::post('/categories/{category}/restore', 'CategoriesController@restore')->name('categories.restore');
    Route::delete('/categories/{category}/delete', 'CategoriesController@delete')->name('categories.delete');
    Route::resource('/categories', 'CategoriesController');

    /**
     * User routes
     */
    Route::resource('/users', 'UsersController');

    /**
     * Profile routes
     */
    Route::get('/profiles/{profile}/edit', 'ProfilesController@edit')->name('profiles.edit');
    Route::put('/profiles/{profile}', 'ProfilesController@update')->name('profiles.update');

    /**
     * Frontblock routes
     */
    Route::resource('/frontblocks', 'FrontblocksController');

    /**
     * Editor routes
     */
    Route::post('/editors', 'EditorsController@store')->name('editors.store');
    Route::delete('/editors/{editor}/destroy', 'EditorsController@destroy')->name('editors.destroy');
});

resources/views/article.blade.php
@extends('layouts.app')

@section('title', $article->title)

@section('top-navbar')
@include('shared.top-navbar')
@endsection

@section('header')
@include('shared.header')
@endsection

@section('categories-navbar')
@include('shared.categories-navbar')
@endsection

@section('footer')
@include('shared.footer')
@endsection

@section('content')
<div class="row">
  <div class="col-lg-9 col-md-12">
    <div class="article-container">
      <div class="row">
        <div class="col-md-12">
          @can('update', $article)
          <a href="{{ route('dashboard.articles.edit', ['id' => $article->id]) }}" target="_blank">Edit this article</a>
          @endcan

          <p class="article-date">{{ $article->created_at->formatLocalized(__('newspaper.date')) }}</p>

          <h1 class="article-title">{{ $article->title }}</h1>
          <p class="article-slug regular-font">{{ $article->slug }}</p>

          <img src="{{ asset('/storage/' . $article->image) }}" alt="" class="img-fluid img-shadow">
        </div>
      </div>

      <hr>

      <!-- Article content -->
      <div class="row">
        <div class="col-md-3">
          <div class="article-tools-container">
            <p>{{ __('newspaper.share') }}</p>
            <ul class="nav">
              <li><img src="/img/logos/facebook.png" alt=""></li>
              <li><img src="/img/logos/twitter.png" alt=""></li>
            </ul>

            <hr>

            <i class="fa fa-tags" style="margin-right: 7px;"></i> 
            <span class="article-tags regular-font">
              @foreach(explode(',', $article->tags) as $tag)
              <a href="#">{{ $tag }}</a>
              @endforeach
            </span>
          </div>
        </div>

        <div class="col-md-9">
          <div class="article-content-container">
            {!! $article->content !!}
          </div>
        </div>
        <!-- / Article content -->
      </div>

      <hr style="margin: 45px 0">

      <!-- Article author -->
      <div class="row">
        <div class="col-md-2 text-center">
          <i class="fa fa-user fa-5x"></i> 
        </div>

        <div class="col-md-10">
          <h4 class="article-author-name regular-font">
            {{ $article->user->profile->name }}
            @if ($article->user->profile->twitter_username)
            <a href="https://twitter.com/{{ $article->user->profile->twitter_username }}" class="article-author-social" target="_blank"><i class="fa fa-twitter"></i></a> 
            @endif
            @if ($article->user->profile->facebook_username)
            <a href="https://facebook.com/{{ $article->user->profile->facebook_username }}" class="article-author-social" target="_blank"><i class="fa fa-facebook"></i></a>
            @endif
          </h4>
          <p class="article-author-bio">{{ $article->user->profile->description }}</p>
        </div>
      </div>
      <!-- / Article author -->
    </div>
  </div>

  @if(count($relatedArticles) > 0)
  <div class="col-lg-3 col-md-12">
    <div class="related-articles-container">
      <h4 class="text-center">You might also like</h4>
      <hr>
      <ul class="list-unstyled related-articles-list">
      @foreach ($relatedArticles as $article)
      <li>
        <a href="{{ route('article', ['id' => $article->id, 'title' => $article->seoUrl()])}}" class="title">
          {{ $article->title }}
        </a>
      </li>
      @endforeach
      </ul>
    </div>
  </div>
  @endif
</div>
@endsection

resources/views/category.blade.php
@extends('layouts.app')

@section('title', config('newspaper.name') . ' - ' . ucfirst($category))

@section('top-navbar')
@include('shared.top-navbar')
@endsection


@section('header')
@include('shared.header')
@endsection

@section('categories-navbar')
@include('shared.categories-navbar')
@endsection

@section('footer')
@include('shared.footer')
@endsection

@section('content')
<div class="row middle-news">
  @foreach ($articles as $article)
  <div class="col-md-4 col-sm-6 middle-news-box">
    <a href="{{ route('article', ['id' => $article->id, 'title' => $article->seoUrl()])}}" class="title">
      @if ($article->image)
      <img src="{{ asset('storage/'.$article->image) }}" class="img-fluid image-shadow frontpage-article-image" alt="">
      @endif
      
      <h4 class="title">{{ $article->title }}</h4>
    </a>
    <h4><small>{{ $article->slug }}</small></h4>
  </div>
  @endforeach
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('top-navbar')
@include('shared.top-navbar')
@endsection

@section('header')
@include('shared.header')
@endsection

@section('categories-navbar')
@include('shared.categories-navbar')
@endsection

@section('footer')
@include('shared.footer')
@endsection

@section('content')
@if($frontblock)
  @include('frontblocks.' . $frontblock->name)
@endif

<hr>

<div class="row">
  @if(count($latestArticles) > 0)
    @foreach($latestArticles as $article)
    <div class="col-md-4 col-sm-6">
      <div class="middle-news-container">
        <a href="{{ route('article', ['id' => $article->id, 'title' => $article->seoUrl()]) }}">
          @if($article->image)
          <img src="{{ asset('storage/'.$article->image) }}" alt="Test" class="img-fluid img-shadow">
          @endif
          <h5 class="regular-font">{{ $article->title }}</h5>
        </a>
        <p class="middle-news-slug">{{ $article->slug }}</p>
      </div>
    </div>
    @endforeach
  @endif
</div>
@endsection