routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('/articles/{title?}/{article}', 'ArticlesController@show')->name('article');
Route::get('/categories/{categoryName}', 'CategoriesController@show')->name('category');

Auth::routes();

Route::group(config('routes.dashboard'), function() {
    Route::get('/', 'IndexController@index')->name('index');

    /**
     * Article routes
     */
    Route::post('/articles/{article}/restore', 'ArticlesController@restore')->name('articles.restore');
    Route::delete('/articles/{article}/delete', 'ArticlesController@delete')->name('articles.delete');
    Route::resource('/articles', 'ArticlesController');

    /**
     * Category routes
     */
    Route::post('/categories/{category}/restore', 'CategoriesController@restore')->name('categories.restore');
    Route::delete('/categories/{category}/delete', 'CategoriesController@delete')->name('categories.delete');
    Route::resource('/categories', 'CategoriesController');

    /**
     * User routes
     */
    Route::resource('/users', 'UsersController');

    /**
     * Profile routes
     */
    Route::get('/profiles/{profile}/edit', 'ProfilesController@edit')->name('profiles.edit');
    Route::put('/profiles/{profile}', 'ProfilesController@update')->name('profiles.update');

    /**
     * Frontblock routes
     */
    Route::resource('/frontblocks', 'FrontblocksController');

    /**
     * Editor routes
     */
    Route::post('/editors', 'EditorsController@store')->name('editors.store');
    Route::delete('/editors/{editor}/destroy', 'EditorsController@destroy')->name('editors.destroy');
});

app/Http/Controllers/Dashboard/ArticlesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\CreateArticle;
use App\Jobs\UpdateArticle;
use App\Queries\ListArticles;
use App\Article;
use App\Category;

class ArticlesController extends Controller
{
    public function index(Request $request, $paginate = 10)
    {
        $this->authorize('list', Article::class);
        
        $articles = ListArticles::dashboard($request, $paginate);

        return view('dashboard.articles.list', [
            'categories' => Category::all(),
            'articles' => $articles
        ]);
    }

    public function create()
    {
        $this->authorize('create', Article::class);

        return view('dashboard.articles.create', [
            'categories' => Category::all()
        ]);
    }

    public function store(Request $request)
    {
        $this->authorize('create', Article::class);
        
        $article = $this->dispatchNow(new CreateArticle(Auth::user(), $request->all()));
        
        return redirect()
            ->action('Dashboard\ArticlesController@edit', ['id' => $article->id])
            ->with('message', 'Article created sucessfully!');
    }

    public function edit(Article $article)
    {
        // Let's not restrict writers from viewing the edit form of
        // articles not belonging to them. Even if they try to submit changes,
        // an auth exception will trigger in update().

        //$this->authorize('update', $article);

        return view('dashboard.articles.edit', [
            'article' => $article,
            'categories' => Category::all()
        ]);
    }

    public function update(Request $request, Article $article)
    {
        $this->authorize('update', $article);

        $this->dispatchNow(new UpdateArticle($article, $request->all()));

        return redirect()
            ->action('Dashboard\ArticlesController@edit', ['id' => $article->id])
            ->with('message', 'Article updated sucessfully!');
    }

    public function delete(Article $article)
    {
        $this->authorize('delete', $article);

        $article->delete();

        return redirect()
            ->action('Dashboard\ArticlesController@edit', ['id' => $article->id])
            ->with('message', 'Article deleted sucessfully!');
    }

    public function destroy(Article $article)
    {
        $this->authorize('destroy', $article);

        $article->forceDelete();

        return redirect()
            ->action('Dashboard\ArticlesController@index')
            ->with('message', 'Article destroyed sucessfully!');
    }

    public function restore(Article $article)
    {
        $this->authorize('restore', $article);
        
        $article->restore();

        return redirect()
            ->action('Dashboard\ArticlesController@edit', ['id' => $article->id])
            ->with('message', 'Article restored sucessfully!');
    }
}

app/Http/Controllers/Dashboard/CategoriesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\CreateCategory;
use App\Jobs\UpdateCategory;
use App\Category;
use App\User;

class CategoriesController extends Controller
{
    public function index()
    {
        $this->authorize('list', Category::class);

        return view('dashboard.categories.list', [
            'categories' => Category::all()
        ]);
    }

    public function store(Request $request)
    {
        $this->authorize('create', Category::class);

        $category = $this->dispatchNow(new CreateCategory($request->all()));

        return redirect()
            ->action('Dashboard\CategoriesController@edit', ['category' => $category->id])
            ->with('message', 'Category created sucessfully!');
    }

    public function edit(Category $category)
    {
        $this->authorize('view', $category);

        $editors = User::where('roles', 'LIKE', '%ROLE_EDITOR%')
            ->get();

        return view('dashboard.categories.edit', [
            'category' => $category,
            'editors' => $editors
        ]);
    }

    public function update(Request $request, Category $category)
    {
        $this->authorize('update', Category::class);

        $this->dispatchNow(new UpdateCategory($category, $request->all()));

        return redirect()
            ->action('Dashboard\CategoriesController@edit', ['category' => $category->id])
            ->with('message', 'Category updated sucessfully!');
    }

    public function delete(Category $category)
    {
        $this->authorize('delete', Category::class);

        $category->delete();

        return redirect()
            ->action('Dashboard\CategoriesController@edit', ['category' => $category->id])
            ->with('message', 'Category deleted sucessfully!');
    }

    public function destroy(Category $category)
    {
        $this->authorize('destroy', Category::class);

        $category->forceDelete();

        return redirect()
            ->action('Dashboard\CategoriesController@index')
            ->with('message', 'Category destroyed sucessfully!');
    }
}

app/Http/Controllers/Dashboard/EditorsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\CreateEditor;
use App\Editor;

class EditorsController extends Controller
{
    public function store(Request $request)
    {
        $this->authorize('create', Editor::class);

        $editor = $this->dispatchNow(new CreateEditor($request->all()));

        return redirect()
            ->action('Dashboard\CategoriesController@edit', ['category' => $editor['category_id']])
            ->with('message', 'Editor added successfully!');
    }

    public function destroy(Editor $editor)
    {
        $this->authorize('delete', Editor::class);

        $category_id = $editor->category_id;

        Editor::destroy($editor->id);

        return redirect()
            ->action('Dashboard\CategoriesController@edit', ['category' => $category_id])
            ->with('message', 'Editor removed successfully!');
    }
}

app/Http/Controllers/Dashboard/FrontblocksController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\UpdateFrontblock;
use App\Frontblock;

class FrontblocksController extends Controller
{
    public function index()
    {
        return view('dashboard.frontblocks.list', [
            'frontblocks' => Frontblock::all()
        ]);
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show(Frontblock $frontblock)
    {
        //
    }

    public function edit(Frontblock $frontblock)
    {
        $this->authorize('update', $frontblock);

        return view('dashboard.frontblocks.edit', [
            'colcounter' => 0,
            'counter' => 0,
            'frontblock' => $frontblock
        ]);
    }

    public function update(Request $request, Frontblock $frontblock)
    {
        $this->authorize('update', $frontblock);

        $this->dispatchNow(new UpdateFrontblock($frontblock, $request->all()));

        return redirect()
            ->action('Dashboard\FrontblocksController@edit', ['frontblock' => $frontblock->id])
            ->with('message', 'Frontblock updated sucessfully!');
    }
    
    public function destroy(Frontblock $frontblock)
    {
        //
    }
}

app/Http/Controllers/Dashboard/IndexController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Article;

class IndexController extends Controller
{
    public function index()
    {
        // TODO: do something better
        $usersCount = User::count();
        $articlesCount = Article::count();
        $commentsCount = rand(7, 120);
        $followersCount = rand(2, 56);

        return view('dashboard.index', [
            'usersCount' => $usersCount,
            'articlesCount' => $articlesCount,
            'commentsCount' => $commentsCount,
            'followersCount' => $followersCount
        ]);
    }
}

app/Http/Controllers/Dashboard/ProfilesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\UpdateProfile;
use App\Profile;

class ProfilesController extends Controller
{
    public function edit(Profile $profile)
    {
        $this->authorize('view', $profile);

        return view('dashboard.profiles.edit', [
            'profile' => $profile
        ]);
    }

    public function update(Request $request, Profile $profile)
    {
        $this->authorize('update', $profile);

        $this->dispatchNow(new UpdateProfile($profile, $request->all()));

        return redirect()
            ->action('Dashboard\ProfilesController@edit', ['id' => $profile->id])
            ->with('message', 'Profile updated sucessfully!');
    }
}

app/Http/Controllers/Dashboard/UsersController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\UpdateUser;
use App\User;

class UsersController extends Controller
{
    public function index()
    {
        $this->authorize('list', User::class);
        
        $users = User::with('profile')->paginate(10);

        return view('dashboard.users.list', [
            'users' => $users
        ]);
    }

    public function edit(User $user)
    {
        $this->authorize('view', $user);

        return view('dashboard.users.edit', [
            'user' => $user
        ]);
    }

    public function update(Request $request, User $user)
    {
        $this->authorize('update', $user);

        $data = $this->dispatchNow(new UpdateUser($user, $request->all()));

        return redirect()
                ->action('Dashboard\UsersController@edit', ['id' => $data['user']->id])
                ->with('message', $data['message']);
    }

    public function destroy(User $user)
    {
        //
    }
}

resources/views/dashboard/footer.blade.php
<footer class="footer">
  <div class="container-fluid">
    <nav class="pull-left">
      <ul>
        <li>
          <a href="{{ route('index') }}">
            Homepage
          </a>
        </li>
      </li>
    </ul>
  </nav>
  <div class="copyright pull-right">
    <span>{{ config('app.name') }} <script>document.write(new Date().getFullYear())</script></span>
  </div>
</div>
</footer>

resources/views/dashboard/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Admin Dashboard')

@section('content')

<!-- top tiles -->
<div class="row tile_count">
	<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
		<span class="count_top"><i class="fa fa-user"></i> Total Users</span>
		<div class="count">2500</div>
		<span class="count_bottom"><i class="green">4% </i> From last Week</span>
	</div>
	<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
		<span class="count_top"><i class="fa fa-clock-o"></i> Average Time</span>
		<div class="count">123.50</div>
		<span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>3% </i> From last Week</span>
	</div>
	<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
		<span class="count_top"><i class="fa fa-user"></i> Total Males</span>
		<div class="count green">2,500</div>
		<span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
	</div>
	<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
		<span class="count_top"><i class="fa fa-user"></i> Total Females</span>
		<div class="count">4,567</div>
		<span class="count_bottom"><i class="red"><i class="fa fa-sort-desc"></i>12% </i> From last Week</span>
	</div>
	<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
		<span class="count_top"><i class="fa fa-user"></i> Total Collections</span>
		<div class="count">2,315</div>
		<span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
	</div>
	<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
		<span class="count_top"><i class="fa fa-user"></i> Total Connections</span>
		<div class="count">7,325</div>
		<span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
	</div>
</div>
<!-- /top tiles -->

<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="dashboard_graph">

			<div class="row x_title">
				<div class="col-md-6">
					<h3>Network Activities <small>Graph title sub-title</small></h3>
				</div>
				<div class="col-md-6">
					<div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
						<i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
						<span>December 30, 2014 - January 28, 2015</span> <b class="caret"></b>
					</div>
				</div>
			</div>

			<div class="col-md-12 col-sm-12 col-xs-12">
				<div id="chart_plot_01" class="demo-placeholder"></div>
			</div>

			<div class="clearfix"></div>
		</div>
	</div>

</div>
<br />
<div class="row">
	<div class="col-md-4 col-sm-4 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Recent Activities <small>Sessions</small></h2>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<div class="dashboard-widget-content">

					<ul class="list-unstyled timeline widget">
						<li>
							<div class="block">
								<div class="block_content">
									<h2 class="title">
										<a>Who Needs Sundance When You’ve Got&nbsp;Crowdfunding?</a>
									</h2>
									<div class="byline">
										<span>13 hours ago</span> by <a>Jane Smith</a>
									</div>
									<p class="excerpt">Film festivals used to be do-or-die moments for movie makers. They were where you met the producers that could fund your project, and if the buyers liked your flick, they’d pay to Fast-forward and… <a>Read&nbsp;More</a>
									</p>
								</div>
							</div>
						</li>
						<li>
							<div class="block">
								<div class="block_content">
									<h2 class="title">
										<a>Who Needs Sundance When You’ve Got&nbsp;Crowdfunding?</a>
									</h2>
									<div class="byline">
										<span>13 hours ago</span> by <a>Jane Smith</a>
									</div>
									<p class="excerpt">Film festivals used to be do-or-die moments for movie makers. They were where you met the producers that could fund your project, and if the buyers liked your flick, they’d pay to Fast-forward and… <a>Read&nbsp;More</a>
									</p>
								</div>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>


	<div class="col-md-8 col-sm-8 col-xs-12">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>Visitors location <small>geo-presentation</small></h2>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<div class="dashboard-widget-content">
							<div class="col-md-4 hidden-small">
								<h2 class="line_30">125.7k Views from 60 countries</h2>

								<table class="countries_list">
									<tbody>
										<tr>
											<td>United States</td>
											<td class="fs15 fw700 text-right">33%</td>
										</tr>
										<tr>
											<td>France</td>
											<td class="fs15 fw700 text-right">27%</td>
										</tr>
										<tr>
											<td>Germany</td>
											<td class="fs15 fw700 text-right">16%</td>
										</tr>
										<tr>
											<td>Spain</td>
											<td class="fs15 fw700 text-right">11%</td>
										</tr>
										<tr>
											<td>Britain</td>
											<td class="fs15 fw700 text-right">10%</td>
										</tr>
									</tbody>
								</table>
							</div>
							<div id="world-map-gdp" class="col-md-8 col-sm-12 col-xs-12" style="height:230px;"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
@endsection

resources/views/dashboard/nav.blade.php
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <img src="images/img.jpg" alt="">Settings
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li>
              <a href="{{ route('dashboard.profiles.edit', ['id' => Auth::user()->id]) }}"> 
                My Profile
              </a>
            </li>
            <li>
              <a href="{{ route('dashboard.users.edit', ['id' => Auth::user()->id]) }}">
                <span>My Account</span>
              </a>
            </li>
            <li>
              <a href="{{ url('/logout') }}"
              onclick="event.preventDefault();
              document.getElementById('logout-form').submit();" target="_top">
              <i class="fa fa-sign-out pull-right"></i> Log Out
            </a>
          </li>
        </ul>
      </li>
      <li class="">
        <a href="javascript:;" class="user-profile dropdown-toggle">
          {{ Auth::user()->profile->name }}
        </a>
      </li>
    </ul>
  </nav>
</div>
</div>

resources/views/dashboard/sidebar.blade.php
{{-- Active <li> class is "current-page" --}}
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
  <div class="menu_section">
    <h3>General</h3>
    <ul class="nav side-menu">
      <li>
        <a href="{{ route('dashboard.index') }}"><i class="fa fa-home"></i> Dashboard</a>
      </li>

      <li>
        <a>
          <i class="fa fa-edit"></i> Articles <span class="fa fa-chevron-down"></span>
        </a>
        <ul class="nav child_menu">
          @can('list', \App\Article::class)
          <li><a href="{{ route('dashboard.articles.index') }}">List</a></li>
          @endcan
          @can('create', \App\Article::class)
          <li><a href="{{ route('dashboard.articles.create') }}">Create</a></li>
          @endcan
          @if(Request::route()->getName() == 'dashboard.articles.edit')
          <li><a href="/{{ Request::path() }}">Update</a></li>
          @endif
         </ul>
      </li>

      @can('list', \App\User::class)
      <li class="{{ ((Request::segment(2) == 'users' 
                  || Request::segment(2) == 'profiles')
                  && !Request::is('dashboard/profiles/'.Auth::user()->id.'/edit') 
                  && !Request::is('dashboard/users/'.Auth::user()->id.'/edit')) 
                  ? 'active' : '' }}">
        <a href="{{ route('dashboard.users.index') }}"><i class="fa fa-users"></i> Users</a>
      </li>
      @endcan

      @can('list', \App\Category::class)
      <li>
        <a href="{{ route('dashboard.categories.index') }}"><i class="fa fa-tags"></i> Categories</a>
      </li>
      @endcan

      @can('list', \App\Frontblock::class)
      <li>
        <a href="{{ route('dashboard.frontblocks.index') }}"><i class="fa fa-table"></i> Frontblocks</a>
      </li>
      @endcan
    </ul>
  </div>

  <div class="menu_section">
    <h3>User</h3>
    <ul class="nav side-menu">
      <li>
        <a href="{{ route('dashboard.profiles.edit', ['id' => Auth::user()->id]) }}">
          <i class="fa fa-user"></i> My Profile
        </a>
      </li>

      <li>
        <a href="{{ route('dashboard.users.edit', ['id' => Auth::user()->id]) }}">
          <i class="fa fa-lock"></i> My Account
        </a>
      </li>

      <li>
        <a href="{{ url('/logout') }}"
        onclick="event.preventDefault();
        document.getElementById('logout-form').submit();" target="_top">
          <i class="fa fa-sign-out"></i> Log out
        </a>
      </li>

      <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
        {{ csrf_field() }}
      </form>
    </ul>
  </div>
</div>