routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('/articles/{title?}/{article}', 'ArticlesController@show')->name('article');
Route::get('/categories/{categoryName}', 'CategoriesController@show')->name('category');

Auth::routes();

Route::group(config('routes.dashboard'), function() {
    Route::get('/', 'IndexController@index')->name('index');

    /**
     * Article routes
     */
    Route::post('/articles/{article}/restore', 'ArticlesController@restore')->name('articles.restore');
    Route::delete('/articles/{article}/delete', 'ArticlesController@delete')->name('articles.delete');
    Route::resource('/articles', 'ArticlesController');

    /**
     * Category routes
     */
    Route::post('/categories/{category}/restore', 'CategoriesController@restore')->name('categories.restore');
    Route::delete('/categories/{category}/delete', 'CategoriesController@delete')->name('categories.delete');
    Route::resource('/categories', 'CategoriesController');

    /**
     * User routes
     */
    Route::resource('/users', 'UsersController');

    /**
     * Profile routes
     */
    Route::get('/profiles/{profile}/edit', 'ProfilesController@edit')->name('profiles.edit');
    Route::put('/profiles/{profile}', 'ProfilesController@update')->name('profiles.update');

    /**
     * Frontblock routes
     */
    Route::resource('/frontblocks', 'FrontblocksController');

    /**
     * Editor routes
     */
    Route::post('/editors', 'EditorsController@store')->name('editors.store');
    Route::delete('/editors/{editor}/destroy', 'EditorsController@destroy')->name('editors.destroy');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\User;
use App\Category;

class Article extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'title',
        'slug',
        'tags',
        'content',
        'status',
        'image',
        'show_image',
        'category_id',
        'user_id'
    ];

    protected $dates = ['deleted_at'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function seoUrl()
    {
        $remove = ['.', '$', ';', ':', '"', '?', '<', '>', '-'];
        $subject = str_replace($remove, '', strtolower($this->title));
        return trim(str_replace([' ', '--'], '-', $subject), '-');
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Article;
use App\Category;

class ArticlesController extends Controller
{
    public function show($title = '', Article $article)
    {
        if ($article->trashed() || $article->status === 'draft') {
            abort(404);
        }

        // don't allow users to modify the optional title segment
        // if they do, redirect them to the correct URI
        if ($article->seourl() !== $title) {
            return redirect()
                ->route('article', [
                    'title' => $article->seoUrl(), 
                    'article' => $article]
                );
        }

        $article = $article->load('user');

        $relatedArticles = Article::where([
                ['category_id', $article->category->id],
                ['id', '<>', $article->id],
                ['status', 'published']
            ])
            ->orderBy('id', 'desc')
            ->take(6)
            ->get();

        return view('article', [
            'categories' => Category::all(),
            'article' => $article,
            'relatedArticles' => $relatedArticles
        ]);
    }
}

app/Http/Controllers/Dashboard/ArticlesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\CreateArticle;
use App\Jobs\UpdateArticle;
use App\Queries\ListArticles;
use App\Article;
use App\Category;

class ArticlesController extends Controller
{
    public function index(Request $request, $paginate = 10)
    {
        $this->authorize('list', Article::class);
        
        $articles = ListArticles::dashboard($request, $paginate);

        return view('dashboard.articles.list', [
            'categories' => Category::all(),
            'articles' => $articles
        ]);
    }

    public function create()
    {
        $this->authorize('create', Article::class);

        return view('dashboard.articles.create', [
            'categories' => Category::all()
        ]);
    }

    public function store(Request $request)
    {
        $this->authorize('create', Article::class);
        
        $article = $this->dispatchNow(new CreateArticle(Auth::user(), $request->all()));
        
        return redirect()
            ->action('Dashboard\ArticlesController@edit', ['id' => $article->id])
            ->with('message', 'Article created sucessfully!');
    }

    public function edit(Article $article)
    {
        // Let's not restrict writers from viewing the edit form of
        // articles not belonging to them. Even if they try to submit changes,
        // an auth exception will trigger in update().

        //$this->authorize('update', $article);

        return view('dashboard.articles.edit', [
            'article' => $article,
            'categories' => Category::all()
        ]);
    }

    public function update(Request $request, Article $article)
    {
        $this->authorize('update', $article);

        $this->dispatchNow(new UpdateArticle($article, $request->all()));

        return redirect()
            ->action('Dashboard\ArticlesController@edit', ['id' => $article->id])
            ->with('message', 'Article updated sucessfully!');
    }

    public function delete(Article $article)
    {
        $this->authorize('delete', $article);

        $article->delete();

        return redirect()
            ->action('Dashboard\ArticlesController@edit', ['id' => $article->id])
            ->with('message', 'Article deleted sucessfully!');
    }

    public function destroy(Article $article)
    {
        $this->authorize('destroy', $article);

        $article->forceDelete();

        return redirect()
            ->action('Dashboard\ArticlesController@index')
            ->with('message', 'Article destroyed sucessfully!');
    }

    public function restore(Article $article)
    {
        $this->authorize('restore', $article);
        
        $article->restore();

        return redirect()
            ->action('Dashboard\ArticlesController@edit', ['id' => $article->id])
            ->with('message', 'Article restored sucessfully!');
    }
}

app/Http/Controllers/Dashboard/CategoriesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\CreateCategory;
use App\Jobs\UpdateCategory;
use App\Category;
use App\User;

class CategoriesController extends Controller
{
    public function index()
    {
        $this->authorize('list', Category::class);

        return view('dashboard.categories.list', [
            'categories' => Category::all()
        ]);
    }

    public function store(Request $request)
    {
        $this->authorize('create', Category::class);

        $category = $this->dispatchNow(new CreateCategory($request->all()));

        return redirect()
            ->action('Dashboard\CategoriesController@edit', ['category' => $category->id])
            ->with('message', 'Category created sucessfully!');
    }

    public function edit(Category $category)
    {
        $this->authorize('view', $category);

        $editors = User::where('roles', 'LIKE', '%ROLE_EDITOR%')
            ->get();

        return view('dashboard.categories.edit', [
            'category' => $category,
            'editors' => $editors
        ]);
    }

    public function update(Request $request, Category $category)
    {
        $this->authorize('update', Category::class);

        $this->dispatchNow(new UpdateCategory($category, $request->all()));

        return redirect()
            ->action('Dashboard\CategoriesController@edit', ['category' => $category->id])
            ->with('message', 'Category updated sucessfully!');
    }

    public function delete(Category $category)
    {
        $this->authorize('delete', Category::class);

        $category->delete();

        return redirect()
            ->action('Dashboard\CategoriesController@edit', ['category' => $category->id])
            ->with('message', 'Category deleted sucessfully!');
    }

    public function destroy(Category $category)
    {
        $this->authorize('destroy', Category::class);

        $category->forceDelete();

        return redirect()
            ->action('Dashboard\CategoriesController@index')
            ->with('message', 'Category destroyed sucessfully!');
    }
}

app/Http/Controllers/Dashboard/EditorsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\CreateEditor;
use App\Editor;

class EditorsController extends Controller
{
    public function store(Request $request)
    {
        $this->authorize('create', Editor::class);

        $editor = $this->dispatchNow(new CreateEditor($request->all()));

        return redirect()
            ->action('Dashboard\CategoriesController@edit', ['category' => $editor['category_id']])
            ->with('message', 'Editor added successfully!');
    }

    public function destroy(Editor $editor)
    {
        $this->authorize('delete', Editor::class);

        $category_id = $editor->category_id;

        Editor::destroy($editor->id);

        return redirect()
            ->action('Dashboard\CategoriesController@edit', ['category' => $category_id])
            ->with('message', 'Editor removed successfully!');
    }
}

app/Http/Controllers/Dashboard/FrontblocksController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\UpdateFrontblock;
use App\Frontblock;

class FrontblocksController extends Controller
{
    public function index()
    {
        return view('dashboard.frontblocks.list', [
            'frontblocks' => Frontblock::all()
        ]);
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show(Frontblock $frontblock)
    {
        //
    }

    public function edit(Frontblock $frontblock)
    {
        $this->authorize('update', $frontblock);

        return view('dashboard.frontblocks.edit', [
            'colcounter' => 0,
            'counter' => 0,
            'frontblock' => $frontblock
        ]);
    }

    public function update(Request $request, Frontblock $frontblock)
    {
        $this->authorize('update', $frontblock);

        $this->dispatchNow(new UpdateFrontblock($frontblock, $request->all()));

        return redirect()
            ->action('Dashboard\FrontblocksController@edit', ['frontblock' => $frontblock->id])
            ->with('message', 'Frontblock updated sucessfully!');
    }
    
    public function destroy(Frontblock $frontblock)
    {
        //
    }
}

app/Http/Controllers/Dashboard/IndexController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Article;

class IndexController extends Controller
{
    public function index()
    {
        // TODO: do something better
        $usersCount = User::count();
        $articlesCount = Article::count();
        $commentsCount = rand(7, 120);
        $followersCount = rand(2, 56);

        return view('dashboard.index', [
            'usersCount' => $usersCount,
            'articlesCount' => $articlesCount,
            'commentsCount' => $commentsCount,
            'followersCount' => $followersCount
        ]);
    }
}

app/Http/Controllers/Dashboard/ProfilesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\UpdateProfile;
use App\Profile;

class ProfilesController extends Controller
{
    public function edit(Profile $profile)
    {
        $this->authorize('view', $profile);

        return view('dashboard.profiles.edit', [
            'profile' => $profile
        ]);
    }

    public function update(Request $request, Profile $profile)
    {
        $this->authorize('update', $profile);

        $this->dispatchNow(new UpdateProfile($profile, $request->all()));

        return redirect()
            ->action('Dashboard\ProfilesController@edit', ['id' => $profile->id])
            ->with('message', 'Profile updated sucessfully!');
    }
}

app/Http/Controllers/Dashboard/UsersController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\UpdateUser;
use App\User;

class UsersController extends Controller
{
    public function index()
    {
        $this->authorize('list', User::class);
        
        $users = User::with('profile')->paginate(10);

        return view('dashboard.users.list', [
            'users' => $users
        ]);
    }

    public function edit(User $user)
    {
        $this->authorize('view', $user);

        return view('dashboard.users.edit', [
            'user' => $user
        ]);
    }

    public function update(Request $request, User $user)
    {
        $this->authorize('update', $user);

        $data = $this->dispatchNow(new UpdateUser($user, $request->all()));

        return redirect()
                ->action('Dashboard\UsersController@edit', ['id' => $data['user']->id])
                ->with('message', $data['message']);
    }

    public function destroy(User $user)
    {
        //
    }
}

resources/views/dashboard/articles/create.blade.php
@extends('layouts.dashboard')

@section('title', 'Admin Dashboard - Create Article')

@section('javascripts')
<script src="//cdn.ckeditor.com/4.7.2/full/ckeditor.js"></script>
<script>CKEDITOR.replace('content');</script>
@endsection

@section('content')
<div class="page-title">
  <div class="title_left">
    <h3>Articles </h3>
  </div>
</div>

<div class="clearfix"></div>

<div class="row">
  <div class="col-xs-12">
    @if (count($errors) > 0)
    <div class="alert alert-danger">
      @foreach ($errors->all() as $error)
      <span>{{ $error }}</span>
      @endforeach
    </div>
    @endif
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="x_panel">
      <div class="x_title">
        <h4 class="title">Create article</h4>
      </div>
      <div class="x_content">
        <form method="POST" action="{{ route('dashboard.articles.store') }}" enctype="multipart/form-data">
          {{ csrf_field() }}

          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label>Title</label>
                <input type="text" class="form-control border-input" name="title" id="name" value="{{ old('title') }}" placeholder="Title">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label>Slug</label>
                <input type="text" class="form-control border-input" name="slug" id="slug" value="{{ old('slug') }}" placeholder="Slug">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label>Content</label>
                <textarea name="content" id="content" class="form-control border-input" cols="30" rows="10">{{ old('content') }}</textarea>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label>Tags</label>
                <input type="text" class="form-control border-input" name="tags" value="{{ old('tags') }}" placeholder="Tags">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <label for="category"><h4>Category</h4></label>
                <select name="category_id" id="category" class="form-control border-input">
                  @foreach ($categories as $category)
                  <option value="{{ $category->id }}">{{ ucfirst($category->name) }}</option>
                  @endforeach
                </select>
              </div>
            </div>

            <div class="col-sm-6">
              <div class="form-group">
                <label for=""><h4>Publish as</h4></label>
                <select name="status" id="" class="form-control border-input">
                  <option value="draft">Draft</option>
                </select>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <label for="">Show image?</label>
                <select name="show_image" id="" class="form-control border-input">
                  <option value="0">No</option>
                  <option value="1">Yes</option>
                </select>
              </div>
            </div>

            <div class="col-sm-6">
              <div class="form-group">
                <label for="">Image file</label>
                <input type="file" id="image" name="image form-control border-input">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-12">
              <div class="form-group">
                <button type="submit" class="btn btn-fill btn-primary"><i class="fa fa-dot-circle-o"></i>Create article</button>
              </div>
            </div>
          </div>

          <div class="clearfix"></div>

        </form>

      </div>
    </div>
  </div>
</div>
@endsection

resources/views/dashboard/articles/edit.blade.php
@extends('layouts.dashboard')

@section('title', 'Admin Dashboard - Editing Article')

@section('javascripts')
<script src="//cdn.ckeditor.com/4.7.2/full/ckeditor.js"></script>
<script>CKEDITOR.replace('content');</script>
@endsection

@section('content')
<div class="page-title">
  <div class="title_left">
    <h3>Articles </h3>
  </div>
</div>

<div class="clearfix"></div>

<div class="row">
  <div class="col-xs-12">
    @if (session('message'))
    <div class="alert alert-success">
      <span>{{ session('message') }}</span>
    </div>
    @endif

    @if (count($errors) > 0)
    <div class="alert alert-danger">
      @foreach ($errors->all() as $error)
      <span>{{ $error }}</span>
      @endforeach
    </div>
    @endif

    @if ($article->trashed())
    <div class="alert alert-danger">
      <span>You are viewing a deleted article. To edit this article, it must be restored by an Editor first.</span>
    </div>
    @endif

    @if ($article->user_id != Auth::id())
    <div class="alert alert-info">
      <span>This article was written by <strong>{{ $article->user->profile->name }}</strong>. Be careful when editing articles that don't belong to you!</span>
    </div>
    @endif
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="x_panel">
      <div class="x_title">
        <div class="pull-left">
          <h4 class="title">Edit article</h4>
        </div>
        <div class="pull-right">
          <h4 class="title"><a href="{{ route('article', ['title' => $article->seoUrl(), 'article' => $article->id]) }}" target="_blank">View article on site</a></h4>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <form method="POST" action="{{ route('dashboard.articles.update', ['id' => $article->id]) }}" enctype="multipart/form-data">
          {{ csrf_field() }}
          <input type="hidden" name="_method" value="PUT">

          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label>Title</label>
                <input type="text" class="form-control border-input" name="title" id="name" value="{{ $article->title }}" placeholder="Title">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label>Slug</label>
                <input type="text" class="form-control border-input" name="slug" id="slug" value="{{ $article->slug }}" placeholder="Slug">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label>Content</label>
                <textarea name="content" id="content" class="form-control border-input" cols="30" rows="10">{{ $article->content }}</textarea>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label>Tags</label>
                <input type="text" class="form-control border-input" name="tags" value="{{ $article->tags }}" placeholder="Tags">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <label for="category">Category</label>
                <select name="category_id" id="category" class="form-control border-input">
                  @foreach ($categories as $category)
                  <option value="{{ $category->id }}"
                    {{ $article->category->id == $category->id ? 'selected=select' : '' }}>
                    {{ ucfirst($category->name) }}
                  </option>
                  @endforeach
                </select>
              </div>
            </div>

            <div class="col-sm-6">
              <div class="form-group">
                <label for="">Status</label>
                <select name="status" id="status" class="form-control border-input">
                  @can('publish', $article)
                  <option value="published" {{ $article->status == 'published' ? 'selected="select"' : '' }}>Published</option>
                  @endcan
                  <option value="draft" {{ $article->status == 'draft' ? 'selected="select"' : '' }}>Draft</option>
                </select>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <label for="">Show image?</label>
                <select name="show_image" id="" class="form-control border-input">
                  <option value="0" {{ $article->show_image == false ? 'selected="select"' : '' }}>No</option>
                  <option value="1" {{ $article->show_image == true ? 'selected="select"' : ''}}>Yes</option>
                </select>
              </div>
            </div>

            <div class="col-sm-6">
              <div class="form-group">
                <label for="">Image file</label>
                <input type="file" id="image" name="image">
              </div>
            </div>
          </div>

          @if (!$article->trashed())
          <div class="row">
            <div class="col-sm-12">
              <div class="form-group">
                <button type="submit" class="btn btn-fill btn-primary"><i class="fa fa-dot-circle-o"></i> Apply changes</button>
              </div>
            </div>
          </div>
          @endif

          <div class="clearfix"></div>

        </form>
      </div>
    </div>
  </div>
</div>

@if (Auth::user()->isEditor() or Auth::user()->isAdmin())
<div class="row">
  <div class="col-md-12">
    <div class="x_panel">
      <div class="x_title">
        <h4 class="title">Danger zone</h4>
      </div>
      <div class="x_content">
        @if ($article->trashed())
        <form method="POST" action="{{ route('dashboard.articles.restore', ['id' => $article->id]) }}">
          {{ csrf_field() }}
          <button class="btn btn-fill btn-primary"><i class="fa fa-ban"></i> Restore article</button>
        </form>
        @else
        <form method="POST" action="{{ route('dashboard.articles.delete', ['id' => $article->id]) }}">
          {{ csrf_field() }}
          <input type="hidden" name="_method" value="DELETE">
          <button class="btn btn-fill btn-danger"><i class="fa fa-ban"></i> Delete article</button>
        </form>
        @endif

        <br>

        @can('destroy', $article)
        <form method="POST" action="{{ route('dashboard.articles.destroy', ['id' => $article->id]) }}">
          {{ csrf_field() }}
          <input type="hidden" name="_method" value="DELETE">
          <button class="btn btn-fill btn-danger"><i class="fa fa-ban"></i> Destroy article</button>
        </form>
        @endcan
      </div>
    </div>
  </div>
</div>
@endif
@endsection

resources/views/dashboard/articles/list.blade.php
@extends('layouts.dashboard')

@section('title', 'Admin Dashboard - Article List')

@section('content')
<div class="page-title">
  <div class="title_left">
    <h3>Articles </h3>
  </div>
</div>

<div class="clearfix"></div>

<div class="row">
  <div class="col-xs-12">
    @if (session('message'))
    <div class="alert alert-info">
      <span>{{ session('message') }}</span>
    </div>
    @endif
    
    @if (count($errors) > 0)
    <div class="alert alert-danger">
      @foreach ($errors->all() as $error)
      <span>{{ $error }}</span>
      @endforeach
    </div>
    @endif
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h4 class="title">Search options</h4>
      </div>

      <div class="x_content">
        <form method="GET" action="{{ route("dashboard.articles.index") }}">
          <div class="row">
            <div class="col-sm-3">
              <div class="form-group">
                <label for="">Status</label>
                <select class="form-control border-input" name="status">
                  <option value="">All</option>
                  <option value="published" {{ Request::input('status') == 'published' ? 'selected' : '' }}>Published</option>
                  <option value="draft" {{ Request::input('status') == 'draft' ? 'selected' : '' }}>Draft</option>
                </select>
              </div>
            </div>

            <div class="col-sm-3">
              <div class="form-group">
                <label for="">Table size</label>
                <select class="form-control border-input" name="paginate">
                  <option value="10">10</option>
                  <option value="25" {{ Request::input('paginate') == '25' ? 'selected' : '' }}>25</option>
                  <option value="50" {{ Request::input('paginate') == '50' ? 'selected' : '' }}>50</option>
                  <option value="100" {{ Request::input('paginate') == '100' ? 'selected' : '' }}>100</option>
                </select>
              </div>
            </div>

            <div class="col-sm-3">
              <div class="form-group">
                <label for="">Title</label>
                <input type="text" value="{{ Request::input('title') }}" name="title" class="form-control border-input" placeholder="Title keywords">
              </div>
            </div>

            <div class="col-sm-3">
              <div class="form-group">
                <label for="">ID</label>
                <input type="number" value="{{ Request::input('id') }}" name="id" class="form-control border-input" placeholder="Article id">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-3">
              <div class="form-group">
                <label for="">Category</label>
                <select class="form-control border-input" name="category_id">
                  <option value="">All</option>
                  @foreach($categories as $category)
                  <option value="{{ $category->id }}" {{ Request::input('category_id') == $category->id ? 'selected' : '' }}>{{ ucfirst($category->name) }}</option>
                  @endforeach
                </select>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-3">
              <div class="form-group">
                {{-- TODO: checkbox seems to have a custom icon which does not work --}}
                <input type="checkbox" name="trashed" value="1" {{ Request::input('trashed') == 1 ? 'checked' : '' }}> Show deleted articles
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-4">
              <button type="submit" class="btn btn-fill btn-primary"><i class="fa fa-dot-circle-o"></i> Apply</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <div class="pull-right">
          <a href="{{ route('dashboard.articles.create') }}">
            <button class="btn btn-fill btn-primary">Create article</button>
          </a> 
        </div>
        <h4 class="title">Article list</h4>
      </div>
      <div class="clearfix"></div>
      <div class="x_content">
        <table class="table table-striped">
          <thead>
            <th>Title</th>
            <th>Writer</th>
            <th>Category</th>
            <th>Last modified</th>
            <th>Status</th>
          </thead>
          <tbody>
            @foreach($articles as $article)
            <tr>
              <td>
                <a href="{{ route('dashboard.articles.edit', ['id' => $article->id]) }}">
                  {{ $article->title }}
                </a>
              </td>
              <td>{{ $article->user->profile->name}}</td>
              <td>
                @if($article->category_id)
                {{ ucfirst($article->category->name) }}
                @else
                Uncategorized
                @endif
              </td>
              <td>{{ $article->updated_at->format('F jS, Y') }}</td>
              <td class="text-center">
                @if ($article->trashed())
                <span class="label label-danger">Deleted</span>
                @elseif ($article->status == 'published')
                <span class="label label-success">
                  {{ ucfirst($article->status) }}
                </span>
                @elseif ($article->status == null)
                <span class="label label-info">
                  Unset
                </span>
                @else
                <span class="label label-info">
                  {{ ucfirst($article->status) }}
                </span>
                @endif
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
      <div class="content">
        {{ $articles->links() }}
      </div>
    </div>
  </div>
</div>
@endsection