routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('/articles/{title?}/{article}', 'ArticlesController@show')->name('article');
Route::get('/categories/{categoryName}', 'CategoriesController@show')->name('category');

Auth::routes();

Route::group(config('routes.dashboard'), function() {
    Route::get('/', 'IndexController@index')->name('index');

    /**
     * Article routes
     */
    Route::post('/articles/{article}/restore', 'ArticlesController@restore')->name('articles.restore');
    Route::delete('/articles/{article}/delete', 'ArticlesController@delete')->name('articles.delete');
    Route::resource('/articles', 'ArticlesController');

    /**
     * Category routes
     */
    Route::post('/categories/{category}/restore', 'CategoriesController@restore')->name('categories.restore');
    Route::delete('/categories/{category}/delete', 'CategoriesController@delete')->name('categories.delete');
    Route::resource('/categories', 'CategoriesController');

    /**
     * User routes
     */
    Route::resource('/users', 'UsersController');

    /**
     * Profile routes
     */
    Route::get('/profiles/{profile}/edit', 'ProfilesController@edit')->name('profiles.edit');
    Route::put('/profiles/{profile}', 'ProfilesController@update')->name('profiles.update');

    /**
     * Frontblock routes
     */
    Route::resource('/frontblocks', 'FrontblocksController');

    /**
     * Editor routes
     */
    Route::post('/editors', 'EditorsController@store')->name('editors.store');
    Route::delete('/editors/{editor}/destroy', 'EditorsController@destroy')->name('editors.destroy');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Article;
use App\Editor;

class Category extends Model
{
    use SoftDeletes;
    
    protected $fillable = ['name'];

    public function articles()
    {
        return $this->hasMany(Article::class);
    }

    public function editors()
    {
        return $this->hasMany(Editor::class);
    }

    public function getNameAttribute($value)
    {
        return ucfirst($value);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class CategoriesController extends Controller
{
    public function show($categoryName)
    {
        $articles = Category::where('name', $categoryName)
            ->firstOrFail()
            ->articles()
            ->where('status', 'published')
            ->orderBy('id', 'DESC')
            ->get();

        return view('category', [
            'category' => $categoryName,
            'categories' => Category::all(),
            'articles' => $articles,
        ]);
    }
}

app/Http/Controllers/Dashboard/ArticlesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\CreateArticle;
use App\Jobs\UpdateArticle;
use App\Queries\ListArticles;
use App\Article;
use App\Category;

class ArticlesController extends Controller
{
    public function index(Request $request, $paginate = 10)
    {
        $this->authorize('list', Article::class);
        
        $articles = ListArticles::dashboard($request, $paginate);

        return view('dashboard.articles.list', [
            'categories' => Category::all(),
            'articles' => $articles
        ]);
    }

    public function create()
    {
        $this->authorize('create', Article::class);

        return view('dashboard.articles.create', [
            'categories' => Category::all()
        ]);
    }

    public function store(Request $request)
    {
        $this->authorize('create', Article::class);
        
        $article = $this->dispatchNow(new CreateArticle(Auth::user(), $request->all()));
        
        return redirect()
            ->action('Dashboard\ArticlesController@edit', ['id' => $article->id])
            ->with('message', 'Article created sucessfully!');
    }

    public function edit(Article $article)
    {
        // Let's not restrict writers from viewing the edit form of
        // articles not belonging to them. Even if they try to submit changes,
        // an auth exception will trigger in update().

        //$this->authorize('update', $article);

        return view('dashboard.articles.edit', [
            'article' => $article,
            'categories' => Category::all()
        ]);
    }

    public function update(Request $request, Article $article)
    {
        $this->authorize('update', $article);

        $this->dispatchNow(new UpdateArticle($article, $request->all()));

        return redirect()
            ->action('Dashboard\ArticlesController@edit', ['id' => $article->id])
            ->with('message', 'Article updated sucessfully!');
    }

    public function delete(Article $article)
    {
        $this->authorize('delete', $article);

        $article->delete();

        return redirect()
            ->action('Dashboard\ArticlesController@edit', ['id' => $article->id])
            ->with('message', 'Article deleted sucessfully!');
    }

    public function destroy(Article $article)
    {
        $this->authorize('destroy', $article);

        $article->forceDelete();

        return redirect()
            ->action('Dashboard\ArticlesController@index')
            ->with('message', 'Article destroyed sucessfully!');
    }

    public function restore(Article $article)
    {
        $this->authorize('restore', $article);
        
        $article->restore();

        return redirect()
            ->action('Dashboard\ArticlesController@edit', ['id' => $article->id])
            ->with('message', 'Article restored sucessfully!');
    }
}

app/Http/Controllers/Dashboard/CategoriesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\CreateCategory;
use App\Jobs\UpdateCategory;
use App\Category;
use App\User;

class CategoriesController extends Controller
{
    public function index()
    {
        $this->authorize('list', Category::class);

        return view('dashboard.categories.list', [
            'categories' => Category::all()
        ]);
    }

    public function store(Request $request)
    {
        $this->authorize('create', Category::class);

        $category = $this->dispatchNow(new CreateCategory($request->all()));

        return redirect()
            ->action('Dashboard\CategoriesController@edit', ['category' => $category->id])
            ->with('message', 'Category created sucessfully!');
    }

    public function edit(Category $category)
    {
        $this->authorize('view', $category);

        $editors = User::where('roles', 'LIKE', '%ROLE_EDITOR%')
            ->get();

        return view('dashboard.categories.edit', [
            'category' => $category,
            'editors' => $editors
        ]);
    }

    public function update(Request $request, Category $category)
    {
        $this->authorize('update', Category::class);

        $this->dispatchNow(new UpdateCategory($category, $request->all()));

        return redirect()
            ->action('Dashboard\CategoriesController@edit', ['category' => $category->id])
            ->with('message', 'Category updated sucessfully!');
    }

    public function delete(Category $category)
    {
        $this->authorize('delete', Category::class);

        $category->delete();

        return redirect()
            ->action('Dashboard\CategoriesController@edit', ['category' => $category->id])
            ->with('message', 'Category deleted sucessfully!');
    }

    public function destroy(Category $category)
    {
        $this->authorize('destroy', Category::class);

        $category->forceDelete();

        return redirect()
            ->action('Dashboard\CategoriesController@index')
            ->with('message', 'Category destroyed sucessfully!');
    }
}

app/Http/Controllers/Dashboard/EditorsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\CreateEditor;
use App\Editor;

class EditorsController extends Controller
{
    public function store(Request $request)
    {
        $this->authorize('create', Editor::class);

        $editor = $this->dispatchNow(new CreateEditor($request->all()));

        return redirect()
            ->action('Dashboard\CategoriesController@edit', ['category' => $editor['category_id']])
            ->with('message', 'Editor added successfully!');
    }

    public function destroy(Editor $editor)
    {
        $this->authorize('delete', Editor::class);

        $category_id = $editor->category_id;

        Editor::destroy($editor->id);

        return redirect()
            ->action('Dashboard\CategoriesController@edit', ['category' => $category_id])
            ->with('message', 'Editor removed successfully!');
    }
}

app/Http/Controllers/Dashboard/FrontblocksController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\UpdateFrontblock;
use App\Frontblock;

class FrontblocksController extends Controller
{
    public function index()
    {
        return view('dashboard.frontblocks.list', [
            'frontblocks' => Frontblock::all()
        ]);
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show(Frontblock $frontblock)
    {
        //
    }

    public function edit(Frontblock $frontblock)
    {
        $this->authorize('update', $frontblock);

        return view('dashboard.frontblocks.edit', [
            'colcounter' => 0,
            'counter' => 0,
            'frontblock' => $frontblock
        ]);
    }

    public function update(Request $request, Frontblock $frontblock)
    {
        $this->authorize('update', $frontblock);

        $this->dispatchNow(new UpdateFrontblock($frontblock, $request->all()));

        return redirect()
            ->action('Dashboard\FrontblocksController@edit', ['frontblock' => $frontblock->id])
            ->with('message', 'Frontblock updated sucessfully!');
    }
    
    public function destroy(Frontblock $frontblock)
    {
        //
    }
}

app/Http/Controllers/Dashboard/IndexController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Article;

class IndexController extends Controller
{
    public function index()
    {
        // TODO: do something better
        $usersCount = User::count();
        $articlesCount = Article::count();
        $commentsCount = rand(7, 120);
        $followersCount = rand(2, 56);

        return view('dashboard.index', [
            'usersCount' => $usersCount,
            'articlesCount' => $articlesCount,
            'commentsCount' => $commentsCount,
            'followersCount' => $followersCount
        ]);
    }
}

app/Http/Controllers/Dashboard/ProfilesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\UpdateProfile;
use App\Profile;

class ProfilesController extends Controller
{
    public function edit(Profile $profile)
    {
        $this->authorize('view', $profile);

        return view('dashboard.profiles.edit', [
            'profile' => $profile
        ]);
    }

    public function update(Request $request, Profile $profile)
    {
        $this->authorize('update', $profile);

        $this->dispatchNow(new UpdateProfile($profile, $request->all()));

        return redirect()
            ->action('Dashboard\ProfilesController@edit', ['id' => $profile->id])
            ->with('message', 'Profile updated sucessfully!');
    }
}

app/Http/Controllers/Dashboard/UsersController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\UpdateUser;
use App\User;

class UsersController extends Controller
{
    public function index()
    {
        $this->authorize('list', User::class);
        
        $users = User::with('profile')->paginate(10);

        return view('dashboard.users.list', [
            'users' => $users
        ]);
    }

    public function edit(User $user)
    {
        $this->authorize('view', $user);

        return view('dashboard.users.edit', [
            'user' => $user
        ]);
    }

    public function update(Request $request, User $user)
    {
        $this->authorize('update', $user);

        $data = $this->dispatchNow(new UpdateUser($user, $request->all()));

        return redirect()
                ->action('Dashboard\UsersController@edit', ['id' => $data['user']->id])
                ->with('message', $data['message']);
    }

    public function destroy(User $user)
    {
        //
    }
}

resources/views/dashboard/categories/edit.blade.php
@extends('layouts.dashboard')

@section('title', 'Admin Dashboard - Editing Category')

@section('content')
<div class="page-title">
  <div class="title_left">
    <h3>Categories </h3>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    @if (session('message'))
    <div class="alert alert-success">
      <span>{{ session('message') }}</span>
    </div>
    @endif

    @if (count($errors) > 0)
    <div class="alert alert-danger">
      @foreach ($errors->all() as $error)
      <span>{{ $error }}</span>
      @endforeach
    </div>
    @endif
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h4 class="title">Edit category</h4>
      </div>
      <div class="x_content">
        <form action="{{ route('dashboard.categories.update', ['id' => $category->id]) }}" method="post">
          {{ csrf_field() }}
          <input type="hidden" name="_method" value="PUT">

          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label>Name</label>
                <input type="text" class="form-control border-input" name="name" id="name" value="{{ $category->name }}" placeholder="Name">
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-12">
              <div class="form-group">
                <button type="submit" class="btn btn-fill btn-primary"><i class="fa fa-dot-circle-o"></i> Apply changes</button>
              </div>
            </div>
          </div>

          <div class="clearfix"></div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h4 class="title">Editors</h4>
      </div>
      <div class="x_content">
        @if(count($category->editors) > 0)
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Name</th>
              <th>Username</th>
              <th>Email</th>
              <th>Options</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($category->editors as $editor)
            <tr>
              <td>{{ $editor->user->profile->name}}</td>
              <td>{{ $editor->user->name }}</td>
              <td>{{ $editor->user->email }}</td>
              <td>
                <form action="{{ route('dashboard.editors.destroy', ['editor' => $editor]) }}" method="post">
                  {{ csrf_field() }}
                  <input type="hidden" name="_method" value="DELETE">

                  <button type="submit" class="btn btn-sm btn-danger">Remove editor</button>
                </form>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
        @else
          <p>This category does not have any editors.</p>
        @endif
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h4 class="title">Add an editor to this category</h4>
      </div>
      <div class="x_content">
        <form action="{{ route('dashboard.editors.store') }}" method="post">
          {{ csrf_field() }}
          <input type="hidden" name="category_id" value="{{ $category->id }}">

          <div class="row">
            <div class="col-md-6">
              <select name="user_id" id="" class="form-control border-input">
                <option value="">Select an editor</option>
                @foreach ($editors as $editor)
                  <option value="{{ $editor->id }}">{{ $editor->profile->name }} ({{ $editor->name }})</option>
                @endforeach
              </select>
            </div>
          </div>

          <br>

          <div class="row">
            <div class="col-md-6">
              <button type="submit" class="btn btn-fill btn-primary">Add editor</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/dashboard/categories/list.blade.php
@extends('layouts.dashboard')

@section('title', 'Admin Dashboard - Categories')

@section('content')
<div class="page-title">
  <div class="title_left">
    <h3>Categories </h3>
  </div>
</div>

<div class="clearfix"></div>

<div class="row">
  <div class="col-xs-12">
    @if (session('message'))
    <div class="alert alert-info">
      <span>{{ session('message') }}</span>
    </div>
    @endif

    @if (count($errors) > 0)
    <div class="alert alert-danger">
      @foreach ($errors->all() as $error)
      <span>{{ $error }}</span>
      @endforeach
    </div>
    @endif
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h4 class="title">Categories</h4>
      </div>
      <div class="clearfix"></div>

      <div class="x_content">
        <table class="table table-hover">
          <thead>
            <th>Name</th>
            <th>Options</th>
          </thead>
          <tbody>
            @foreach($categories as $category)
            <tr>
              <td>
                <a href="{{ route('dashboard.categories.edit', ['id' => $category->id]) }}">{{ ucfirst($category->name) }}</a>
              </td>
              <td>
                <i class="fa fa-trash fa-lg"></i>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h4 class="title">Create new category</h4>
      </div>
      <div class="x_content">
        <form action="{{ route('dashboard.categories.store') }}" method="post">
          {{ csrf_field() }}

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="">Name</label>
                <input type="text" id="name" name="name" class="border-input form-control" placeholder="Name">
              </div> 
            </div>
          </div>

          <div class="row">
            <div class="col-md-6">
              <div class="form-group form-actions">
                <button type="submit" class="btn btn-fill btn-primary">Create</button>
              </div>
            </div>
          </div>

        </form>
      </div>
    </div>
  </div>
</div>
@endsection